"""add_user_role

Revision ID: 38e956c34cc6
Revises: 1d9aaa0499e7
Create Date: 2024-12-06 20:17:50.535691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '38e956c34cc6'
down_revision: Union[str, None] = '1d9aaa0499e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = ENUM("USER", "ADMIN", name="userrole", create_type=False)
    userrole_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')

    userrole_enum = ENUM("USER", "ADMIN", name="userrole", create_type=False)
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
